# Generated by Django 5.2.6 on 2025-10-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='happy_customers',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='projects_completed',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='services_offered',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='support_hours',
        ),
        migrations.RemoveField(
            model_name='companyconfig',
            name='years_experience',
        ),
    ]
