# Generated by Django 5.2.6 on 2025-10-08 18:25

import gallery.fields
import gallery.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=gallery.fields.AutoCleanImageField(upload_to=gallery.models.upload_to),
        ),
    ]
