# Generated by Django 5.2.6 on 2025-10-08 18:30

import gallery.fields
import gallery.models
import gallery.storage_backends
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=gallery.fields.AutoCleanImageField(storage=gallery.storage_backends.SupabaseStorage(), upload_to=gallery.models.upload_to),
        ),
    ]
