# Generated by Django 5.2.6 on 2025-10-05 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_remove_companyconfig_happy_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyconfig',
            name='email',
        ),
    ]
