# Generated by Django 5.2.6 on 2025-11-20 13:13

import gallery.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_alter_portfolioitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyconfig',
            name='email_from_address',
            field=models.EmailField(blank=True, help_text="'From' email address. If empty, uses email username", max_length=254),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_host',
            field=models.CharField(blank=True, default='smtp.gmail.com', help_text='SMTP host (e.g., smtp.gmail.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_password',
            field=gallery.fields.EncryptedCharField(blank=True, help_text="Email account password or app-specific password. Spaces are preserved (e.g., 'slim bruw vyeo wnce')", max_length=255),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_port',
            field=models.PositiveIntegerField(default=587, help_text='SMTP port (typically 587 for TLS or 465 for SSL)'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_to_address',
            field=models.EmailField(blank=True, help_text='Email address to receive contact form submissions. If empty, sends to email username', max_length=254),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_use_tls',
            field=models.BooleanField(default=True, help_text='Use TLS encryption (uncheck for SSL)'),
        ),
        migrations.AddField(
            model_name='companyconfig',
            name='email_username',
            field=models.EmailField(blank=True, help_text='Email account username/address for sending emails', max_length=254),
        ),
    ]
