# Generated by Django 5.2.6 on 2025-11-20 11:40

import gallery.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_companyconfig_email_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='email_password',
            field=gallery.fields.EncryptedCharField(blank=True, help_text="Email account password or app-specific password. Spaces are preserved (e.g., 'slim bruw vyeo wnce')", max_length=255),
        ),
    ]
