# Generated by Django 5.2.6 on 2025-12-02 09:32

import gallery.fields
import gallery.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_companyconfig_email_from_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=gallery.fields.AutoCleanImageField(upload_to=gallery.models.upload_to),
        ),
    ]
